framework:
    cache:
        prefix_seed: symfony-test/app
        app: cache.adapter.redis
        #app: cache.adapter.apcu
        default_redis_provider: '%env(REDIS_CACHE_URL)%'
        pools:
            cache.app.countries:
                adapter: cache.app
            cache.app.users:
                adapter: cache.app
                #public: false
                #default_lifetime: 60
            cache.flysystem.psr6:
                adapter: cache.adapter.filesystem
            #cache.flysystem.psr6:
                #adapter: cache.app

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Core\AppCacheManager:
        bind:
            Symfony\Contracts\Cache\CacheInterface $countriesCache: '@cache.app.countries'
            Symfony\Contracts\Cache\CacheInterface $usersCache: '@cache.app.countries'

        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
