# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
            #local:
                #directory: '%kernel.project_dir%/public/%uploads_dir_name%'
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter
            #alias: League\Flysystem\Filesystem
        cached_uploads_filesystem:
            adapter: public_uploads_adapter
            cache: psr6_app_cache

    cache:
        psr6_app_cache:
            psr6:
                service: cache.flysystem.psr6
